import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const PdfPrinter = require('pdfmake/src/printer');

import NutritionLog from '../models/NutritionLog.js';
import User from '../models/User.js';

const fonts = {
  Helvetica: {
    normal:      'Helvetica',
    bold:        'Helvetica-Bold',
    italics:     'Helvetica-Oblique',
    bolditalics: 'Helvetica-BoldOblique'
  }
};

export const generateNutritionReport = async (req, res, next) => {
  try {
    const user  = await User.findById(req.user._id);
    const start = new Date(req.query.startDate || Date.now() - 7 * 86400000);
    start.setHours(0,0,0,0);
    const end = new Date(req.query.endDate || Date.now());
    end.setHours(23,59,59,999);

    const logs = await NutritionLog.find({ user: req.user._id, date: { $gte: start, $lte: end } }).sort({ date: 1 });

    const avg = (f) => logs.length ? Math.round(logs.reduce((s,l) => s + l[f], 0) / logs.length) : 0;

    // Table body
    const tableBody = [[
      { text: 'Date',       style: 'th' },
      { text: 'Calories',   style: 'th' },
      { text: 'Protein (g)',style: 'th' },
      { text: 'Carbs (g)',  style: 'th' },
      { text: 'Fat (g)',    style: 'th' },
      { text: 'Water (ml)', style: 'th' }
    ]];

    for (const log of logs) {
      tableBody.push([
        new Date(log.date).toLocaleDateString('en-US', { month:'short', day:'numeric' }),
        Math.round(log.totalCalories).toString(),
        Math.round(log.totalProtein).toString(),
        Math.round(log.totalCarbs).toString(),
        Math.round(log.totalFat).toString(),
        log.waterIntake.toString()
      ]);
    }

    const docDefinition = {
      content: [
        { text: 'AI Nutrition Dashboard',         style: 'header',    alignment: 'center' },
        { text: 'Personalized Nutrition Report',  style: 'subheader', alignment: 'center' },
        { canvas: [{ type: 'line', x1:0, y1:2, x2:515, y2:2, lineWidth:1, lineColor:'#4CAF50' }] },
        { text: '\n' },
        {
          columns: [
            { text: [{ text:'User: ', bold:true }, user.name, '\n',
                     { text:'Email: ', bold:true }, user.email, '\n',
                     { text:'Period: ', bold:true },
                     `${start.toLocaleDateString()} – ${end.toLocaleDateString()}`] },
            { text: [{ text:'Daily Goal: ', bold:true }, `${user.dailyCalorieGoal} kcal\n`,
                     { text:'Protein Goal: ', bold:true }, `${user.dailyProteinGoal}g\n`,
                     { text:'Generated: ', bold:true }, new Date().toLocaleDateString()],
              alignment:'right' }
          ]
        },
        { text: '\n' },
        { text: 'Weekly Averages', style: 'sectionHeader' },
        {
          columns: [
            { stack:[{ text: avg('totalCalories')+' kcal', style:'stat', color:'#4CAF50' }, { text:'Avg Calories', style:'statLabel' }], alignment:'center' },
            { stack:[{ text: avg('totalProtein')+'g',      style:'stat', color:'#2196F3' }, { text:'Avg Protein',  style:'statLabel' }], alignment:'center' },
            { stack:[{ text: avg('totalCarbs')+'g',        style:'stat', color:'#FF9800' }, { text:'Avg Carbs',    style:'statLabel' }], alignment:'center' },
            { stack:[{ text: avg('totalFat')+'g',          style:'stat', color:'#F44336' }, { text:'Avg Fat',      style:'statLabel' }], alignment:'center' }
          ],
          margin: [0,10,0,10]
        },
        { text: 'Daily Log', style: 'sectionHeader' },
        { table: { headerRows:1, widths:['*','*','*','*','*','*'], body: tableBody }, layout:'lightHorizontalLines' },
        { text: '\n' },
        ...(logs.some(l => l.aiAnalysis) ? [
          { text: 'AI Analysis', style: 'sectionHeader' },
          { text: logs.find(l => l.aiAnalysis)?.aiAnalysis || '', style:'body', margin:[0,5,0,0] }
        ] : []),
        { text: '\nGenerated by AI Nutrition Dashboard  •  ' + new Date().toLocaleString(), style:'footer', alignment:'center' }
      ],
      styles: {
        header:       { font:'Helvetica', fontSize:22, bold:true, color:'#2E7D32', margin:[0,0,0,4] },
        subheader:    { font:'Helvetica', fontSize:14, color:'#666', margin:[0,0,0,12] },
        sectionHeader:{ font:'Helvetica', fontSize:13, bold:true, color:'#333', margin:[0,12,0,4] },
        th:           { font:'Helvetica', bold:true, fontSize:10, color:'white', fillColor:'#4CAF50' },
        stat:         { font:'Helvetica', fontSize:22, bold:true },
        statLabel:    { font:'Helvetica', fontSize:9,  color:'#666' },
        body:         { font:'Helvetica', fontSize:10 },
        footer:       { font:'Helvetica', fontSize:9, color:'#999', italics:true }
      },
      defaultStyle: { font:'Helvetica', fontSize:10 }
    };

    const printer = new PdfPrinter(fonts);
    const pdfDoc  = printer.createPdfKitDocument(docDefinition);

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="nutrition-report-${start.toISOString().split('T')[0]}.pdf"`);
    pdfDoc.pipe(res);
    pdfDoc.end();
  } catch (err) { next(err); }
};
